# ドラム音色定義ファイル (GM1準拠)
# 各ノート番号に対応するドラム音色パラメータを定義
#
# デフォルト値:
#   pitch=69  volume=1.00  attack=0.00
#   hold=0.00 decay=0.30   pan=0.50

[drum.24]
caption = "Unknown Note:24"
pitch   = 64
volume  = 2.00
pan     = 0.35

[drum.25]
caption = "Unknown Note:25"
pitch   = 57
volume  = 1.50
attack  = 0.05
decay   = 1.00

[drum.26]
caption = "Unknown Note:26"
pitch   = 81
volume  = 2.00
decay   = 0.20

[drum.27]
caption = "High Q"
pitch   = 64
volume  = 2.00
decay   = 0.20

[drum.28]
caption = "Slap"
volume  = 2.00
pan     = 0.42

[drum.29]
caption = "Scratch Push"
volume  = 1.80

[drum.30]
caption = "Scratch Pull"
pitch   = 66
volume  = 1.80
decay   = 0.40

[drum.31]
caption = "Sticks"
volume  = 3.00
decay   = 0.20

[drum.32]
caption = "Square Click"
volume  = 2.00
decay   = 0.10

[drum.33]
caption = "Metronome Click"
pitch   = 66
volume  = 2.00
decay   = 0.10

[drum.34]
caption = "Metronome Bell"
pitch   = 78
volume  = 2.00

[drum.35]
caption = "Acoustic Bass Drum"
pitch   = 32
volume  = 4.59
decay   = 0.20

[drum.36]
caption = "Bass Drum 1"
pitch   = 32
volume  = 4.50
decay   = 0.25

[drum.37]
caption = "Side Stick"
pitch   = 64
volume  = 2.00

[drum.38]
caption = "Acoustic Snare"
pitch   = 44
volume  = 4.00
decay   = 0.40

[drum.39]
caption = "Hand Clap"
pitch   = 57
volume  = 2.00
hold    = 0.05
decay   = 0.40
pan     = 0.42

[drum.40]
caption = "Electric Snare"
pitch   = 64
volume  = 3.00
decay   = 0.40

[drum.41]
caption = "Low Floor Tom"
pitch   = 44
volume  = 3.00
decay   = 0.50
pan     = 0.27

[drum.42]
caption = "Closed Hi-Hat"
pitch   = 64
volume  = 1.60
hold    = 0.05
decay   = 0.10
pan     = 0.66

[drum.43]
caption = "High Floor Tom"
pitch   = 46
volume  = 3.00
decay   = 0.50
pan     = 0.36

[drum.44]
caption = "Pedal Hi-Hat"
pitch   = 66
volume  = 1.60
hold    = 0.05
decay   = 0.10
pan     = 0.66

[drum.45]
caption = "Low Tom"
pitch   = 48
volume  = 3.00
decay   = 0.50
pan     = 0.45

[drum.46]
caption = "Open Hi-Hat"
pitch   = 70
volume  = 1.60
hold    = 0.10
decay   = 0.75
pan     = 0.66

[drum.47]
caption = "Low-Mid Tom"
pitch   = 50
volume  = 3.00
decay   = 0.40
pan     = 0.55

[drum.48]
caption = "Hi-Mid Tom"
pitch   = 53
volume  = 3.00
decay   = 0.40
pan     = 0.64

[drum.49]
caption = "Crash Cymbal 1"
pitch   = 68
volume  = 2.00
decay   = 2.00
pan     = 0.66

[drum.50]
caption = "High Tom"
pitch   = 56
volume  = 3.50
decay   = 0.40
pan     = 0.73

[drum.51]
caption = "Ride Cymbal 1"
pitch   = 66
volume  = 2.50
decay   = 1.50
pan     = 0.35

[drum.52]
caption = "Chinese Cymbal"
pitch   = 62
volume  = 2.00
decay   = 1.00
pan     = 0.35

[drum.53]
caption = "Ride Bell"
pitch   = 80
volume  = 2.00
decay   = 1.00
pan     = 0.35

[drum.54]
caption = "Tambourine"
pitch   = 100
volume  = 2.00
decay   = 0.20
pan     = 0.58

[drum.55]
caption = "Splash Cymbal"
pitch   = 70
volume  = 1.60
decay   = 1.50
pan     = 0.42

[drum.56]
caption = "Cowbell"
pitch   = 60
volume  = 3.00
decay   = 0.40
pan     = 0.66

[drum.57]
caption = "Crash Cymbal 2"
pitch   = 72
volume  = 2.00
decay   = 1.50
pan     = 0.35

[drum.58]
caption = "Vibraslap"
pitch   = 60
volume  = 2.00
decay   = 1.50
pan     = 0.22

[drum.59]
caption = "Ride Cymbal 2"
pitch   = 76
volume  = 1.20
decay   = 1.50
pan     = 0.35

[drum.60]
caption = "Hi Bongo"
pitch   = 70
volume  = 2.00
decay   = 0.20
pan     = 0.77

[drum.61]
caption = "Low Bongo"
pitch   = 64
volume  = 2.00
pan     = 0.77

[drum.62]
caption = "Mute Hi Conga"
pitch   = 70
volume  = 3.00
decay   = 0.10
pan     = 0.30

[drum.63]
caption = "Open Hi Conga"
pitch   = 67
volume  = 2.00
pan     = 0.30

[drum.64]
caption = "Low Conga"
pitch   = 58
volume  = 2.00
decay   = 0.35
pan     = 0.35

[drum.65]
caption = "High Timbale"
pitch   = 70
volume  = 2.00
decay   = 0.40
pan     = 0.66

[drum.66]
caption = "Low Timbale"
pitch   = 64
volume  = 2.00
decay   = 0.40
pan     = 0.66

[drum.67]
caption = "High Agogo"
pitch   = 70
volume  = 2.00
decay   = 0.20
pan     = 0.22

[drum.68]
caption = "Low Agogo"
pitch   = 64
volume  = 2.00
decay   = 0.20
pan     = 0.22

[drum.69]
caption = "Cabasa"
pitch   = 70
volume  = 2.50
decay   = 0.15
pan     = 0.22

[drum.70]
caption = "Maracas"
pitch   = 66
volume  = 2.00
decay   = 0.20
pan     = 0.19

[drum.71]
caption = "Short Whistle"
pitch   = 71
volume  = 2.00
hold    = 0.10
decay   = 0.10
pan     = 0.77

[drum.72]
caption = "Long Whistle"
volume  = 2.00
hold    = 0.30
decay   = 0.10
pan     = 0.77

[drum.73]
caption = "Short Guiro"
pitch   = 70
volume  = 2.50
decay   = 0.15
pan     = 0.73

[drum.74]
caption = "Long Guiro"
pitch   = 68
volume  = 1.50
hold    = 0.30
decay   = 0.10
pan     = 0.73

[drum.75]
caption = "Claves"
pitch   = 76
volume  = 2.00
decay   = 0.20
pan     = 0.66

[drum.76]
caption = "Hi Wood Block"
pitch   = 70
volume  = 2.00
pan     = 0.77

[drum.77]
caption = "Low Wood Block"
pitch   = 64
volume  = 2.00
pan     = 0.77

[drum.78]
caption = "Mute Cuica"
pitch   = 70
volume  = 2.00
decay   = 0.40
pan     = 0.35

[drum.79]
caption = "Open Cuica"
pitch   = 64
volume  = 2.00
decay   = 0.40
pan     = 0.35

[drum.80]
caption = "Mute Triangle"
pitch   = 86
volume  = 2.00
decay   = 0.35
pan     = 0.19

[drum.81]
caption = "Open Triangle"
pitch   = 86
volume  = 0.70
hold    = 0.10
decay   = 0.20
pan     = 0.19
