# メロディ音色定義: Piano (0-7) / Chromatic Percussion (8-15)

# --- Piano (0-7) ---
[melody.0]
caption = "Acoustic Grand Piano"
volume  = 1.00
attack  = 0.02
hold    = 0.00
decay   = 3.00
sustain = 0.00
fade    = 0.00
release = 1.00

[melody.1]
caption = "Bright Acoustic Piano"
volume  = 1.00
attack  = 0.02
hold    = 0.00
decay   = 5.00
sustain = 0.00
fade    = 0.00
release = 1.00

[melody.2]
caption = "Electric Grand Piano"
volume  = 1.00
attack  = 0.02
hold    = 0.00
decay   = 5.00
sustain = 0.00
fade    = 0.00
release = 1.00

[melody.3]
caption = "Honky-tonk Piano"
volume  = 1.00
attack  = 0.02
hold    = 0.00
decay   = 5.00
sustain = 0.00
fade    = 0.00
release = 1.00

[melody.4]
caption = "Electric Piano 1"
volume  = 1.00
attack  = 0.02
hold    = 0.00
decay   = 5.00
sustain = 0.00
fade    = 0.00
release = 1.00

[melody.5]
caption = "Electric Piano 2"
volume  = 1.00
attack  = 0.02
hold    = 0.00
decay   = 5.00
sustain = 0.00
fade    = 0.00
release = 1.00

[melody.6]
caption = "Harpsichord"
volume  = 1.00
attack  = 0.02
hold    = 0.00
decay   = 5.00
sustain = 0.00
fade    = 0.00
release = 1.00

[melody.7]
caption = "Clavinet"
volume  = 1.00
attack  = 0.02
hold    = 0.00
decay   = 6.00
sustain = 0.00
fade    = 0.00
release = 0.10

# --- Chromatic Percussion (8-15) ---
[melody.8]
caption = "Celesta"
volume  = 1.00
attack  = 0.02
hold    = 0.00
decay   = 4.00
sustain = 0.00
fade    = 0.00
release = 1.50

[melody.9]
caption = "Glockenspiel"
volume  = 1.00
attack  = 0.02
hold    = 0.00
decay   = 4.00
sustain = 0.00
fade    = 0.00
release = 2.00

[melody.10]
caption = "Music Box"
volume  = 1.00
attack  = 0.02
hold    = 0.00
decay   = 4.00
sustain = 0.00
fade    = 0.00
release = 2.00

[melody.11]
caption = "Vibraphone"
volume  = 1.00
attack  = 0.02
hold    = 0.00
decay   = 7.00
sustain = 0.00
fade    = 0.00
release = 1.00

[melody.12]
caption = "Marimba"
volume  = 1.00
attack  = 0.02
hold    = 0.00
decay   = 3.00
sustain = 0.00
fade    = 0.00
release = 2.00

[melody.13]
caption = "Xylophone"
volume  = 1.00
attack  = 0.02
hold    = 0.00
decay   = 3.00
sustain = 0.00
fade    = 0.00
release = 2.00

[melody.14]
caption = "Tubular Bells"
volume  = 1.00
attack  = 0.02
hold    = 0.00
decay   = 7.00
sustain = 0.00
fade    = 0.00
release = 5.00

[melody.15]
caption = "Dulcimer"
volume  = 1.00
attack  = 0.02
hold    = 0.00
decay   = 3.00
sustain = 0.00
fade    = 0.00
release = 2.00
